### ISSUE TITLE
A bug in your bug game?

### ISSUE THREAD

**Issue by jtenner** [DVLP/LinkOfDeath#13]
![Image of bug](http://i.snag.gy/FJ0QO.jpg)

I might be able to investigate it and help.  Thoughts?

**Comment by DVLP** [comment]
Is that IE6 ?

Just kidding. What browser are you using and what are the steps to reproduce this bug?

**Comment by jtenner** [comment]
Nope. Chrome [latest].  Try overriding the context menu event.

``` javascript
window.addEventListener('contextmenu', function(e) {
  e.preventDefault();
  return false;
});
```

**Comment by DVLP** [comment]
This seems like a fair workaround for the problem, but I think that the cause might lie in a plugin or something else. This is interesting because even after focusing on the link using TAB the browser crashes so I'm curious how is the context menu being triggered. Are you clicking RMB or context button on your keyboard?

**Comment by jtenner** [comment]
I simply right clicked and moved the mouse button, it stops reporting mousemove events at that point so the LOD hovers around the right click position.

The bug fix is probably required :).

'contextmenu' should trigger no matter how the context menu opens.

**Comment by DVLP** [comment]
It's like right-clicking anywhere else i.e. flash games. I don't think there's a need to change default browser behaviour for right click in this case.
